//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_FreshShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuGiamGia
    {
        public int Ma { get; set; }
        public string Macode { get; set; }
        public Nullable<System.DateTime> Ngayapdung { get; set; }
    }
}
