//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_FreshShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuNhap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuNhap()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int Ma { get; set; }
        public Nullable<int> Mancc { get; set; }
        public Nullable<int> MaSP { get; set; }
        public Nullable<System.DateTime> Ngaynhap { get; set; }
        public Nullable<decimal> Giasi { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> lastModifyDate { get; set; }
        public Nullable<int> lastModifyBy { get; set; }
        public Nullable<int> Soluong { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NhaCungCap NhaCungCap { get; set; }
        public virtual SP SP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Reports { get; set; }
    }
}
