//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KLTN_FreshShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Ma { get; set; }
        public Nullable<int> MaPhieuNhap { get; set; }
        public Nullable<System.DateTime> NgayIn { get; set; }
        public Nullable<bool> isDelete { get; set; }
        public Nullable<System.DateTime> lastModifyDate { get; set; }
        public Nullable<int> lastModifyBy { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual PhieuNhap PhieuNhap { get; set; }
    }
}
